// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaAPI.Data;

#nullable disable

namespace PruebaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427235312_m4")]
    partial class m4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("PruebaAPI.Models.Tabla1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tabla1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Descripcion = "Descripción de Juan",
                            Nombre = "Juan"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            Descripcion = "Descripción de María",
                            Nombre = "María"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "López",
                            Descripcion = "Descripción de Carlos",
                            Nombre = "Carlos"
                        });
                });

            modelBuilder.Entity("PruebaAPI.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Edad = 20,
                            Matricula = 1,
                            Nombre = "Juan",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Edad = 22,
                            Matricula = 2,
                            Nombre = "María",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Edad = 23,
                            Matricula = 3,
                            Nombre = "Carlos",
                            Tipo = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
